### ISSUE TITLE
Pass title as options to be displayed in gitter-chat-action-bar

### ISSUE THREAD

**Issue by BerkeleyTrue** [gitterHQ/sidecar#26]
At the moment we are having to identify the embed window we want and then do some jQuery magic to add a box with title. This includes some fiddling with css to get it to fit in. A clean solution would be to pass a title or display room title as an option on chat instantiation.

**Comment by MadLittleMods** [comment]
Hey @BerkeleyTrue,

I added [`examples/room-title-on-target`](https://github.com/gitterHQ/sidecar/blob/master/examples/room-title-on-target/index.html) but this example was only possible through a bit of rework.

There was no reason why the action bar was added in `EMBEDCHATONCE`, so I moved that out and is now available when `gitter-sidecar-instance-started` and `gitter-chat-started` events are fired.

This means that adding titles is as easy as *(from [`examples/room-title-on-target`](https://github.com/gitterHQ/sidecar/blob/master/examples/room-title-on-target/index.html))*:

```js
document.addEventListener('gitter-sidecar-instance-started', function(e) {
  var chat = e.detail.chat;
  chat.options.targetElement.forEach(function(targetElement) {
    var actionBarElement = targetElement.querySelector('.gitter-chat-embed-action-bar');
    actionBarElement.insertAdjacentHTML('afterbegin', '<div class="chat-embed-title">' + chat.options.room + '</div>');
  });
});
```

**Comment by BerkeleyTrue** [comment]
Looks good!
