### ISSUE TITLE
Emit event on EMBEDCHATONCE

### ISSUE THREAD

**Issue by BerkeleyTrue** [gitterHQ/sidecar#27]
We are adding a title to our chat bar(see https://github.com/gitterHQ/sidecar/issues/26). We are having to add a call once function on 'gitter-chat-toggle' to embed our title in 'gitter-embed-action-bar'.

**Comment by MadLittleMods** [comment]
This use case has been superceded by the solution here: https://github.com/gitterHQ/sidecar/issues/26#issuecomment-149419963
