### ISSUE TITLE
Array.from is not a function

### ISSUE THREAD

**Issue by manuelmazzuola** [gitterHQ/sidecar#28]
Getting an error visiting the page https://sidecar.gitter.im/ with Chrome version `44.0.2403.157 (64-bit)`

`/dist/sidecar.v1.js:5 Uncaught TypeError: Array.from is not a function`

**Comment by MadLittleMods** [comment]
Thank you for the report, we don't use [`Array.from`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from#Browser_compatibility) in any of our code but it looks like it might be in a dependency or getting introduced in the build process.

**Comment by melvincarvalho** [comment]
Same issue

`Version 43.0.2357.130 Ubuntu 14.10 (64-bit)`

http://taskify.org/test.html

Uncaught TypeError: Array.from is not a function

**Comment by melvincarvalho** [comment]
PS works in opera and firefox ...

**Comment by MadLittleMods** [comment]
It looks like ["Comprehensions" are a babel caveat](https://babeljs.io/docs/advanced/caveats/) that require `Array.from`.

I added a polyfill to ease the pain and it is in production now: `v1.1.2`
