### ISSUE TITLE
Close button is hidden behind Drupal's admin bar

### ISSUE THREAD

**Issue by tormi** [gitterHQ/sidecar#34]
I have a problem when using sidecar - chat's close button is hidden behind [Drupal 8](http://drupal.org/) admin bar (black bar with edit link) when user is logged in to Drupal:

![gitter](https://cloud.githubusercontent.com/assets/146800/11584034/dec0b714-9a68-11e5-9c80-8c127fc92bb9.PNG)

**Comment by mydigitalself** [comment]
Tom you can override the CSS, if you inspect the sidecar area you can see the relevant classes and increase the z-index.

**Comment by MadLittleMods** [comment]
@tormi You can use CSS to increase the `z-index` of `.gitter-chat-embed` and `.gitter-open-chat-button` to appear in front of the admin bar.

Instead of fighting 3rd party styles which could easily be `9999999`, we leave it a sensible amount and allow others to modify as needed
