### ISSUE TITLE
Clicking login even while logged into GitHub does not show chat.

### ISSUE THREAD

**Issue by Icehunter** [gitterHQ/sidecar#38]
http://awsbb.com/ is my site and the code was added here:

https://github.com/awsbb/awsbb.github.io/blob/master/index.html#L82

I have this issue on other sites as well. The chat will show in the box but login just refreshes it and I'm unable to type from the site.

The following link is attached to that button and opening it manually works and I can type: https://gitter.im/awsbb/awsbb/~embed# 

Is there anything I'm doing wrong? The only thing I see in chrome logs is:

```
[Faye] Marking underlying websocket as failed
```

Thanks for your help in advance!

**Comment by MadLittleMods** [comment]
@Icehunter I can chat while already being logged in and login starting from the sidecar frame, just fine.

 - Can you share a gif/video of what is happening to you?
 - Try logging out of GitHub and signing back in

**Comment by Icehunter** [comment]
Finally figured out the issue... I had "block third party cookies and site data" selected in Chrome settings. After adding my site, Gitter and GitHub it all works now.

Sorry for the inconvenience ><
