### ISSUE TITLE
How to i18n "Open Chat"?

### ISSUE THREAD

**Issue by bebraw** [gitterHQ/sidecar#41]
Hi,

What's the right way to i18n the "Open Chat" text?

I could hack around the current API. Just wondering if there's a neat way to override it.

**Comment by MadLittleMods** [comment]
Hey @bebraw,

There are a couple options:

Listen when the Sidecar starts and edit the button text. Same concept as the [room title on chat example](https://github.com/gitterHQ/sidecar/tree/master/examples/room-title-on-target).

```js
document.addEventListener('gitter-sidecar-instance-started', function(e) {
  var chat = e.detail.chat;
  chat.options.activationElement.forEach(function(activationElement) {
    activationElement.innerHTML = 'Avoin Keskustelu'
  });
});
```

Or create a custom [`option.activationElement`](https://github.com/gitterHQ/sidecar/blob/master/API.md#options) with your text.

**Comment by bebraw** [comment]
@MadLittleMods Gotcha! Thanks.

It might be cool if it was possible to pass the string through `options`.

Nice try with Finnish. :wink:

**Comment by bebraw** [comment]
The latter method worked perfectly. Here's a [React wrapper](https://github.com/survivejs/site/blob/master/components/Gitter.jsx) if you are interested.
