### ISSUE TITLE
Adjust basic position properties of window.

### ISSUE THREAD

**Issue by Ward9250** [gitterHQ/sidecar#50]
I'm using sidecar with a mkdocs generated documentation site. So far I've managed to use a custom js file which is specified in mkdocs. You can see the page here: https://biojulia.github.io/Bio.jl/latest/
The open chat button works. However mkdocs pages have a fixed navbar at the top, which prevents you from getting to the buttons at the top to close the chat pane.
How can I get it so as either the chat window 1). comes out on top of the fixed navbar, 2). is not too tall and so does not go under the navbar, or 3). Just slides the entire page to the side as it comes out?

**Comment by MadLittleMods** [comment]
@Ward9250 You can customize Sidecar with your own CSS. It looks like that is what you are curerntly doing :+1:

Adjust the `z-index` of `.gitter-chat-embed`, adjust the `top` or add some padding.
