### ISSUE TITLE
[Request] Create userscript/addons for main browsers

### ISSUE THREAD

**Issue by Bluscream** [gitterHQ/sidecar#55]
The closest i've seen was https://chrome.google.com/webstore/detail/gitter-helper-for-github/apahfabdianobklhejoojcpmoegaolpi

Instead I would love to see this Sidecar available on GitHub pages that are either connected to a gitter room or have a Gitter badge in their README

**Comment by MadLittleMods** [comment]
It's up to the project owner whether they want a Gitter badge in their readme.

Feel free to create your own extension that injects a badge or Sidecar on the page.

**Comment by Bluscream** [comment]
Can i use the API to check whether there is a connected Gitter room or not?

**Comment by MadLittleMods** [comment]
@Bluscream Yes, two ways to go about it

 - `POST https://api.gitter.im/v1/rooms` with `{"uri":"gitterhq/sandbox"}`
 - `GET https://gitter.im/gitterhq/sandbox` and look for the 200

**Comment by Bluscream** [comment]
Awsome, thanks 👍
