### ISSUE TITLE
“Refused to display 'https://github.com/login…' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".”

### ISSUE THREAD

**Issue by sideshowbarker** [gitterHQ/sidecar#57]
A `https://github.com/login?client_id=NNN&return_to=%2Flogin%…26state%3DNN` document appears to be trying to get loaded by sidecar in the sidecar frame (if a user clicks the **Sign in with Github** button)—but github explicitly disallows that by sending a CSP header with `frame-ancestors 'none'` and also an `X-Frame-Options: deny` header.

> Load denied by X-Frame-Options: `https://github.com/login?client_id=NNN&return_to=…` does not permit framing.

It’s unclear to me how I might be able to work around this—or how it could ever work to begin with for anybody else either, given the github.com/login CSP policy &  `X-Frame-Options: deny`  header.

**Comment by sideshowbarker** [comment]
I notice the same issue if a user clicks the **Sign in with Twitter** button:

> Load denied by X-Frame-Options: https://api.twitter.com/oauth/authenticate?oauth_token=NNN does not permit cross-origin framing.

**Comment by mydigitalself** [comment]
@sideshowbarker when you click on the Login button from sidecar, you should get a popup window, the login window shouldn't be loaded into the frame. Can you confirm what you are seeing with some screenshots perhaps?

I've just tested it again now and it works just fine.

**Comment by sideshowbarker** [comment]
@mydigitalself sorry for not replying on this before now—I’ve been away

Anyway, the page I’ve been trying to make this work on is https://sideshowbarker.net/

It does seem to be trying to load the login window in the frame

**Comment by MadLittleMods** [comment]
@sideshowbarker It looks like you are trying to use Sidecar with a private room(one to one room). You can only use public rooms with Sidecar.

**Comment by sideshowbarker** [comment]
> @sideshowbarker It looks like you are trying to use Sidecar with a private room(one to one room). You can only use public rooms with Sidecar.

Ah OK thanks—didn’t know about that limitation
