### ISSUE TITLE
Fade covering up message - various warnings and errors 

### ISSUE THREAD

**Issue by etisdew** [gitterHQ/sidecar#60]
I had to pull my use of this due to an error: The resource https://cdn03.gitter.im/_s/7327a0f/fonts/sourcesans/SourceSansPro-ExtraLight.otf.woff was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.

This error occurs for each of the fonts, and appears my text doesn't have a font due to the failure to load? Worked perfectly until I tried to implement on a new ui element however backtracking my changes I'm unable to see anything that would be influencing that behavior and it remains broken in a previously working state. 

Watching the logs I find this: 
```
router-embed-chat.js:sourcemap:6 Uncaught TypeError: this.showWelcomeMessage is not a function
    at constructor.autojoin (router-embed-chat.js:sourcemap:6)
    at constructor.execute (vendor.js:1)
    at Object.callback (vendor.js:1)
    at vendor.js:1
    at Function.M.some.M.any (vendor.js:1)
    at t.History.loadUrl (vendor.js:1)
    at t.History.start (vendor.js:1)
    at router-embed-chat.js:sourcemap:1
    at n.handleEvent (router-embed-chat.js:sourcemap:1)
```

Part(3): see attached
![errorish](https://user-images.githubusercontent.com/26851121/28293286-41bf839c-6b08-11e7-957c-4c9602ee0159.jpg)

**Comment by MadLittleMods** [comment]
The font warnings don't affect usage but you can follow for any updates, https://gitlab.com/gitlab-org/gitter/webapp-temp-issues-for-move/issues/29

I've created a fix for the `showWlecomeMessage is not a function` error but that only occurs if you login and join the room, https://gitlab.com/gitlab-org/gitter/webapp/merge_requests/1085

I am curious what version of Chrome and what OS you are using? There is an issue showing the very first message in a room but the menu bar white fade shouldn't be extending that far, ex. https://i.imgur.com/tMH21WG.png

**Comment by etisdew** [comment]
Sorry for my great delay in following this issue up. I believe the issue was coming up in Chrome's LTS and Windows 7. however I was able to resolve it with random luck? I will be experimenting with sidecar again over the next five days if you'd like to connect. I believe the side effect was coupled to the fonts I was using somehow but I'm likely to recreate the issue if it is a real issue.

Going to close this issue for the time being though.
