### ISSUE TITLE
WIKI Help Image

### ISSUE THREAD

**Issue by mpage24** [gitterHQ/sidecar#61]
I was trying to find out some information and utilized the wiki help.  The image shown is one of the earlier versions, and did not have the radio buttons I needed help with.  So, if wiki help could be updated to the current version that would be helpful.  I am running Vulnerator_v6-1-9
The information I need help with is what is the difference between the NIST SP 800-53 Revision 3 and Revision 4 selection.  Does Revision 4 radio button include the additional security controls that the NIST documentation mentions?  Does selection Revision 4 ensure that those controls are looked at?
![radio_buttons](https://user-images.githubusercontent.com/30475203/28633957-8792a514-7203-11e7-8c0f-947bef420e60.png)

**Comment by MadLittleMods** [comment]
I assume you posted on the wrong project.

**Comment by mpage24** [comment]
I believe i did, sorry about that.  I had to email them.
