### ISSUE TITLE
Sidecar popup stays in background 

### ISSUE THREAD

**Issue by pditommaso** [gitterHQ/sidecar#62]
Hi, I've just found Gitter sidecar and I would like to include in my website. However it appears under the GitHub ribbon and the layout top bar (in the screen shot below, ignore the 404 error because it's a test on the localhost). 

Is there a way to customise the CSS to make it appear in foreground?

![screen shot 2017-08-01 at 22 06 08](https://user-images.githubusercontent.com/816968/28844801-278b569a-7706-11e7-9967-d09672e52245.png)

**Comment by MadLittleMods** [comment]
See https://github.com/gitterHQ/sidecar/issues/34#issuecomment-161955358

**Comment by pditommaso** [comment]
Thanks!
