### ISSUE TITLE
NPM Invalid

### ISSUE THREAD

**Issue by etisdew** [gitterHQ/sidecar#63]
Getting a 404 on the readme.md links to NPM and invalid in your widget. What is the status of that?

Sidecar rocks and I'd love to make this one of my first projects to get involved with but I don't know where to start.

My name is Jeff and I'm trying to integrate with you for a part of a bootcamp I think using this correctly would be quite impressive, just reassigning the input to a sibling instead of a child of the chat area (or making it appear that way), remove the background and skipping the fonts, Not really sure where to start. Would it be easiest if I just overwrote the stylings?

**Comment by MadLittleMods** [comment]
Hey @etisdew, thanks for the report 😀  I have contacted npm support to see what happened there, https://www.npmjs.com/package/gitter-sidecar

You can't change the font or any stylings inside the chat iframe itself as that is just part of the normal [webapp](https://gitlab.com/gitlab-org/gitter/webapp).

**Comment by MadLittleMods** [comment]
Thanks for keeping up on this @etisdew ❤️ 

I have been back and forth with npm support and haven't got a confirmation yet but https://www.npmjs.com/package/gitter-sidecar seems to be available again :tada:
